[build-system]
requires = [
	"setuptools",
	"setuptools-scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "pan2met"
description = "Reconstruct metabolic network from (pan)genome"
dynamic = ["version"]
authors = [
	{ name = "Samuel Ortion" },
]
maintainers = [
	{ name = "Samuel Ortion" },
]
readme = "README.md"
keywords = ["Pangenomics", "Metabolism", "Bioinformatics", "Prokaryote"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"Natural Language :: English",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Python :: 3",
	"Topic :: Scientific/Engineering :: Bio-Informatics"
]
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
	"aiosql>=15.0,<16",
	"SPARQLWrapper",
	"clyngor>=1.0.0,<2",
	"padmet>=5.0.3,<6",
	"cerberus>=1.3.8",
	"duckdb>=1.5.6",
	"ouisparql",
	"pyyaml>=6.0.3",
]

[project.optional-dependencies]
doc = [
	"sphinx",
	"sphinx_rtd_theme",
	"readthedocs-sphinx-search",
	"sphinx-autobuild",
]
test = [
	"pytest>=9.1.1",
	"pytest-cov>=7.1.0",
]


[project.urls]
# Homepage = ""
Repository = "https://github.com/labgem/pan2met"
Documentation = "https://pan2met.readthedocs.io/"

[project.scripts]
pan2met = "pan2met.__main__:main"

[tool.setuptools.dynamic]
version = { file = "VERSION" }

[tool.pixi.workspace]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]


[tool.pixi.environments]
default = { features = ["doc", "test"], solve-group = "default" }
doc = { features = ["doc"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
prod = { features = [], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.14.*"
pip = ">=26.0.1,<27"
graph-tool = ">=3"
cerberus = ">=1.3.8,<2"
yaml = ">=0.2.5,<0.3"
pyyaml = ">=6.0.3,<7"
tqdm = ">=4.70.1,<5"
[tool.uv.workspace]
members = [
    "worktree/benchmark/benchmark",
]

[tool.uv.sources]
ouisparql = { git = "https://gitlab.com/sortion/ouisparql", rev = "47e47688cf461506e6f565f340742f543d3873b2" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
