[build-system]
requires = [
	"setuptools",
	"setuptools-scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "pan2met"
description = "Reconstruct metabolic network from (pan)genome"
dynamic = ["version"]
authors = [
	{ name = "Samuel Ortion" },
]
maintainers = [
	{ name = "Samuel Ortion" },
]
readme = "README.md"
keywords = ["pangenomics", "metabolism", "bioinformatics", "prokaryote"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"Natural Language :: English",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Python :: 3",
	"Topic :: Scientific/Engineering :: Bio-Informatics"
]
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
	"aiosql>=15.0,<16",
]
[project.optional-dependencies]
doc = [
	"sphinx",
	"sphinx_rtd_theme",
	"readthedocs-sphinx-search",
	"sphinx-autobuild",
]
test = [
	"pytest>=9.0.2",
	"pytest-cov",
]
viz = [
	"bokeh"
]
padmet = [
	"padmet>=5.0.3,<6",
]

[project.urls]
# Homepage = ""
Repository = "https://github.com/labgem/pan2met"
# Documentation = ""

[project.scripts]
pan2met = "pan2met.__main__:main"

[tool.setuptools.dynamic]
version = { file = "VERSION" }

[tool.pixi.workspace]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pan2met = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
doc = { features = ["doc"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
viz = { features = ["viz"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.14.*"
pip = ">=26.0.1,<27"
graph-tool = ">=3"
pytest = ">=9.1.1,<10"
