[build-system]
requires = [
	"setuptools",
	"setuptools-scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "pangenome2panmetabolome"
description = "Reconstruct (pan)metabolome based on (pan)genome"
dynamic = ["version"]
authors = [
	{ name = "Samuel Ortion" },
]
maintainers = [
	{ name = "Samuel Ortion" },
]
readme = "README.md"
keywords = ["pangenomics", "metabolism", "bioinformatics", "prokaryote"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"License :: OSI Approved :: CEA CNRS Logiciel Libre License, version 2.1 (CeCILL-2.1)",
	"Natural Language :: English",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Python :: 3",
	"Topic :: Scientific/Engineering :: Bio-Informatics"
]
# requires-python = ">=3.9" # ?

dependencies = [
	"numpy",
	"h5py",
	"hdf5plugin",
	"pybiopax",
	"aiosql",
	"sparqlwrapper",
	"python-dotenv",
	"pythoncyc",
	#"clyngor", # "pip install git+https://github.com/Aluriak/clyngor@master",
	"ouisparql",
	"pytest>=9.0.2",
	"psycopg>=3.3.2",
	"mpwt>=0.8.8",
]

license = { file = "LICENSE" }

[project.optional-dependencies]
doc = [
	"sphinx",
	"sphinx_rtd_theme",
	"readthedocs-sphinx-search",
	"sphinx-autobuild"
]
test = [
	"pytest"
]

[project.urls]
# Homepage = ""
Repository = "https://gitlab.com/sortion/pangenome2panmetabolome"
# Documentation = ""

[project.scripts]
pangenome2panmetabolome = "pangenome2panmetabolome.cli:main"

[tool.setuptools.dynamic]
version = { file = "VERSION" }

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pangenome2panmetabolome = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
doc = { features = ["doc"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.tasks]
