[reactome]

[reactome.asp]
metacyc_gpr = "./tmp/metacyc_gpr.lp"
metacyc_reverse_gpr = "./tmp/metacyc_reverse_gpr.lp"

[inference]
pathway_score_threshold = 0.15
pathway_completion_threshold = 0.5

[inference.rules]
taxonomic_range=true
pathway_species=true
pathway_uniqueness=true
pathway_key_reaction=true
pathway_ontology=true
pathway_variant=true

[inference.weights]
# this value must be > 1 to be effective.
taxonomic_range_boost=1.2
# must be above 1 too.
neighbor_species_boost=1.2

[reference]
ncbi_taxonomy = /mnt/shared/bank/NCBI-Taxonomy/taxdmp_2026-01-01
source = metabiantes

[metabiantes]
database = metabiantes
