"""
Explore the input pangenome graph to get an insight on the (pan)-genomic context
of genes implied in the same pathway.
Rationale: we expect genes involved in the same pathway to have a tendency to be colocated in a genome,
or even, be the member of the same strains, hence to the same cloud region in the pangenome graph.

We base our analysis on the pangenome graph generated by PPanGGOLiN as a first approach.
"""

import logging
from typing import Dict, Iterable, Tuple
from pathlib import Path

import tqdm
import tables
import graph_tool
import graph_tool.topology


logger = logging.getLogger("pan2met")
logger.setLevel(logging.DEBUG)


def graph_from_ppanggolin(
    ppanggolin_file: Path,
) -> Tuple[Dict[str, int], graph_tool.Graph]:
    """
    Read the graph from PPanGGOLiN HDF5 with PPanGGOLiN API

    :param panggolin_file: The path to a PPanGGOLiN HDF5 file

    :returns: A mapping from monomer id to graph node id and the graph-tool undirected graph.
    """
    pangenome = tables.File(ppanggolin_file, mode="r")
    edges: Iterable[Tuple[str, str]] = pangenome.get("edges")

    vmap: dict[str, int] = {}
    g: graph_tool.Graph = graph_tool.Graph(directed=False)
    g.vp["id"] = g.new_vp("string")
    # Create the vertices
    for edge in edges:
        u, v = edge
        for label in [u, v]:
            vertex = g.add_vertex()
            vmap[label] = vertex
    # Add the edges
    for edge in tqdm.tqdm(edges):
        u_label, v_label = edge
        u_vertex = vmap[u_label]
        v_vertex = vmap[v_label]
        if not g.edge(u_vertex, v_label):
            g.add_edge(u_vertex, v_vertex)
    return vmap, g


def main():
    G = graph_from_ppanggolin(
        Path("/home/sortion/data/pangbank/GTDB_refseq_s__Escherichia_coli_id615.h5")
    )
    monomer_1: str = "GCF_023600545.1_CDS_4492"
    monomer_2: str = "GCF_001679985.1_CDS_0000"
    vertex_path, _edge_list = graph_tool.topology.shortest_path(
        G, source=monomer_1, target=monomer_2
    )
    distance = len(vertex_path) - 2
    print(distance)


if __name__ == "__main__":
    main()
